#!/usr/bin/env bash
# Usage: sub <command> [<args>]
# Summary: Welcome to subspace, an easy way to namespace subcommands

set -e

# Original command
base=$(basename $0)

# Current working directory
cwd=$(pwd)

# Path that was called
path="${BASH_SOURCE[@]}"

# Add root dir to path
if [[ $path =~ (^[\./])(.*)(/"$base") ]]; then
   if [[ "/" = "${BASH_REMATCH[1]}" ]]; then
      export _SUB_ROOT="${path%/*/$base}"
   else
      root=$(dirname "$cwd${BASH_REMATCH[2]}")
      abs_path="$cwd${BASH_REMATCH[2]}"
      export _SUB_ROOT="${abs_path%/*}"
   fi
else
   echo "Invalid path to $base"
   exit 1
fi

# Add lib dir to path
export PATH="$_SUB_ROOT/libexec:$PATH"

# Parse commands
command="$1"
case "$command" in
# Help command
"" | "-h" | "--help" )
   if [[ ! -x "$base-help" ]]; then
      exec "$base-help" >&2
      exit 1
   fi
   ;;
# All other commands
* )
   command_path="$(command -v "$base-$command" || true)"

   if [[ ! -x "$command_path" ]]; then
      echo "$base: no such command '$command'" >&2
      exit 1
   fi

   shift
   exec "$command_path" "$@"
   ;;
esac
