#!/usr/bin/env bash

set -e

resolve_link() {
   $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
   local cwd="$(pwd)"
   local path="$1"

   while [ -n "$path" ]; do
      cd "${path%/*}"
      local name="${path##*/}"
      path="$(resolve_link "$name" || true)"
   done

   pwd
   cd "$cwd"
}

base=$(basename $0)
lib="$(abs_dirname "$0")"
export _SUB_ROOT="$(abs_dirname "$lib")"
export PATH="${lib}:$PATH"

command="$1"
# Help command
case "$command" in
"" | "-h" | "--help" )
   exec "$base-help"
   ;;
# Enable autocompletion
"--complete" )
   echo --path
   ;;
# Handle all other commands
* )
   command_path="$(command -v "$base-$command" || true)"

   if [ ! -x "$command_path" ]; then
      echo "$base: no such command \`$command'" >&2
      exit 1
   fi

   shift
   exec "$command_path" "$@"
   ;;
esac
