#!/usr/bin/env bash
# Usage: sub list
# Summary: List commands in your sub library

for file in $( ls $_SUB_ROOT/libexec ); do
 	if [[ $file =~ ^[^-]*$ ]]; then
    	if [[ -x $file ]]; then
       	echo $file
    	fi
 	fi
done