#!/usr/bin/env bash
# Print and format command usage, summary, and help info
# Usage: sub help [<command>]

set -e

command="$1"
case "$command" in
"" ) 
   printf "Summary:\n\n%-5s%-60s\n\n" "" "$($SUB_COMMAND helper summary $SUB_COMMAND)"
   printf "Usage:\n\n%-5s%-60s\n\n" "" "$($SUB_COMMAND helper usage $SUB_COMMAND)"
   printf "%s\n\n" "$($SUB_COMMAND commands)"
   printf "%s\n\n" "See '$SUB_COMMAND help <command>' for information on a specific command."
   ;;
* )
   usage="$($SUB_COMMAND helper usage $command)"

   if [[ ! -x "$_SUB_ROOT/libexec/$SUB_COMMAND-$command" ]]; then
      echo "$SUB_COMMAND: no such command '$command'" >&2
      exit 1
   elif [[ -n "$usage" ]]; then
      summary="$($SUB_COMMAND helper summary $command)"
      if [[ -n $summary ]]; then
         printf "Summary:\n\n%-5s%s\n\n" "" "$summary"
      fi

      printf "Usage:\n\n%-5s%s\n\n" "" "$usage"

      help="$($SUB_COMMAND helper help $command)"
      if [[ -n $help ]]; then
         printf "Help:\n\n%s\n\n" "$help"
      fi

   else
      printf "Usage:\n\n%-5s%s\n\n" "" "Command not documented"
   fi
esac
