#!/usr/bin/env bash
# Usage: sub launch <command>
# Summary: Launch a new subspace
# Help: Launch a new executable into Subspace.

command="$1"

if [[ -z $command ]]
then
	echo "Usage: sub launch <command>"
	echo "Please provide a launch command"
	exit 0
fi

path="$_SUB_ROOT/libexec/$command"
link="$_SUB_ROOT/bin/$command"

if [[ -e $path ]]
then
  	echo "ERROR: $path already exists"
elif [[ -L "$link" ]]
then
  	echo "ERROR: $link already exists"
else
	# Add new command
  	cp "$_SUB_ROOT/libexec/sub" "$path"
  	chmod 755 $path
  	ln -s $path $link

  	# Add help command
  	cp "$_SUB_ROOT/libexec/sub-help" "$path-help"
  	chmod 755 "$path-help"

    # Enable command listing
    cp "$_SUB_ROOT/libexec/sub-commands" "$path-commands"
    chmod 755 "$path-commands"

    # Enable completions
    # cp "$_SUB_ROOT/libexec/sub-completions" "$path-completions"
    # chmod 755 "$path-completions"
    # exec "$base completions"

  	echo "$command command has been created!"
  	echo "Edit your command at $path"
fi