#!/usr/bin/env bash
# Usage: sub launch <command>
# Summary: Launch a new executable into subspace
# Help: Launch creates a new executable in your subspace.
# Your new command is added to the subspace path and comes
# with these default subcommands:
#
#      <command> commands
#      <command> help
#
# After launching, you can create more subcommands for
# your new command by following the naming scheme in
# your subspace library.

command="$1"

if [[ -z $command ]]
then
   usage="$($base helper usage $command)"
   printf "Usage:\n\n%-5s%s\n\n" "" "$usage"
   echo "Please provide a launch command"
   exit 0
fi

path="$SUB_ROOT/libexec/$command"
link="$SUB_ROOT/bin/$command"

if [[ -e $path ]]
then
   echo "ERROR: $path already exists"
elif [[ -L "$link" ]]
then
   echo "ERROR: $link already exists"
else
   # Add new command
   cp "$SUB_ROOT/libexec/sub" "$path"
   chmod 755 $path
   ln -s $path $link
   sed -i "s/$SUB_COMMAND\( \|$\)/$command\1/g" "$path"
   sed -i "s/\(# Summary: \)\(.*$\)/\1New command in subspace. Add your subcommands!/g" "$path"
   sed -i "/^# Help: /{n;d}" "$path"
   sed -i "s/^program=.*/program=$command/" "$path"
   sed -i "s/^version=.*/version=\"version not specified\"/" "$path"

   # Add help command
   cp "$SUB_ROOT/libexec/sub-help" "$path-help"
   chmod 755 "$path-help"
   sed -i "s/$SUB_COMMAND\( \|$\)/$command\1/g" "$path-help"

   # Enable command listing
   cp "$SUB_ROOT/libexec/sub-commands" "$path-commands"
   chmod 755 "$path-commands"
   sed -i "s/$SUB_COMMAND\( \|$\)/$command\1/g" "$path-commands"

   printf "%s\n\n%-5s%s\n\n" "Command created! Edit your command at:" "" "$path"
fi