#!/usr/bin/env bash
# Usage: sub commands [-l]
# Summary: List all sub commands
# Help: Autocompletion and checking if command already exists

set -e

flag="$1"
case "$flag" in
# Human-readable list
"" )
   $SUB_COMMAND helper commands
   ;;
# Machine-readable list
"-l" | "--list" )
   $SUB_COMMAND helper commands -l
   ;;
esac