#!/usr/bin/env bash
# Usage: sub launch <command>
# Summary: Launch a new executable into subspace
# Help: Launch creates a new executable in subspace. Your
# new command is added to the subspace path and comes
# with these subcommands by default:
#
#      <command> commands
#      <command> help
#
# After launching, you can create more subcommands for
# your new command by following the naming scheme in
# your subspace library.

command="$1"

if [[ -z $command ]]
then
   echo "Usage:

      sub launch <command>
   "
   echo "Please provide a launch command"
   exit 0
fi

path="$_SUB_ROOT/libexec/$command"
link="$_SUB_ROOT/bin/$command"

if [[ -e $path ]]
then
   echo "ERROR: $path already exists"
elif [[ -L "$link" ]]
then
   echo "ERROR: $link already exists"
else
   # Add new command
   cp "$_SUB_ROOT/libexec/sub" "$path"
   chmod 755 $path
   ln -s $path $link

   # Add help command
   cp "$_SUB_ROOT/libexec/sub-help" "$path-help"
   chmod 755 "$path-help"

   # Enable command listing
   cp "$_SUB_ROOT/libexec/sub-commands" "$path-commands"
   chmod 755 "$path-commands"

   # Enable completions
   # cp "$_SUB_ROOT/libexec/sub-completions" "$path-completions"
   # chmod 755 "$path-completions"
   # exec "$base completions"

   printf "%s\n\n%-5s%s\n\n" "Command created! Edit your command at:" "" "$path"
fi