#!/usr/bin/env bash
# Usage: sub commands [-l]
# Summary: List all sub commands
# Help: Autocompletion and checking if command already exists

set -e

base="$(basename $0)"
base="${base%-commands}"

args="$1"
case "$args" in
# Human-readable list
"" )
   $base helper commands
   ;;
# Machine-readable list
"-l" | "--list" )
   $base helper commands -l
   ;;
esac