#!/usr/bin/env bash
set -e

resolve_link() {
   $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
   local cwd="$(pwd)"
   local path="$1"

   while [ -n "$path" ]; do
      cd "${path%/*}"
      local name="${path##*/}"
      path="$(resolve_link "$name" || true)"
   done

   pwd
   cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _SUB_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

command="$1"
case "$command" in
"" | "-h" | "--help" )
   exec sub-help
   ;;
# Generate a new command
"-n" | "--new" )
   path="$_SUB_ROOT/libexec/$2"
   link="$_SUB_ROOT/bin/$2"
   if [[ -e $path ]]
   then
      echo "ERROR: $path already exists"
   elif [[ -L "$link" ]]
   then
      echo "ERROR: $link already exists"
   else
      touch "$path"
      echo "#!/usr/bin/env bash" >> "$path"
      chmod 755 $path
      ln -s $path $link
      echo "$2 command has been created! Edit your command at $path"
   fi
   ;;
"--test")
   echo "$(command -v "sub-$command")"
   ;;
* )
   command_path="$(command -v "sub-$command" || true)"

   if [ ! -x "$command_path" ]; then
      echo "sub: no such command \`$command'" >&2
      exit 1
   fi

   echo "$(command -v "sub-$command")"

   shift
   exec "$command_path" "$@"
   ;;
esac
